[package]
name = "gen95"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
catppuccin-egui = "4.0"
eframe = "0.26.2"
